# Auto-generated by support/gen_rwf_catalogue.py — do not edit by hand.
# Source: src/eq.c (RWF dispatch table).
# Regenerate after any change to eq.c by running:
#     python3 support/gen_rwf_catalogue.py

# Each entry: name -> (param_count, eqtype_mask_int, note_str)
#   eqtype_mask: bitmask of EQTYPE_* flags; 0xFFFF = EQTYPE_ALL
#   note: short pitfall hint surfaced by linter --strict mode

EQTYPE_ALL = 0xFFFF

EQTYPE_BITS = {
    'EQTYPE_TESTRECALC'     : 0x0001,
    'EQTYPE_TESTVALIDATE'   : 0x0002,
    'EQTYPE_L1VALIDATE'     : 0x0004,
    'EQTYPE_ANALYSER'       : 0x0008,
    'EQTYPE_REQUEST_ADD'    : 0x0010,
    'EQTYPE_REQUEST_RM'     : 0x0020,
    'EQTYPE_REPORT'         : 0x0040,
    'EQTYPE_TESTACCEPT'     : 0x0080,
    'EQTYPE_GENERIC'        : 0x0100,
    'EQTYPE_AUTOVAL'        : 0x0200,
    'EQTYPE_REGISTRATION'   : 0x0400,
    'EQTYPE_REPDISP'        : 0x0800,
    'EQTYPE_MBSCHECK'       : 0x1000,
    'EQTYPE_MFA'            : 0x2000,
    'EQTYPE_BILLING'        : 0x4000,
    'EQTYPE_RETRIGGER'      : 0x8000,
}

SUBROUTINES = {
    'abs'                           : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'exp'                           : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'ln'                            : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'log'                           : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'sqrt'                          : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'max'                           : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'min'                           : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'int'                           : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'pow'                           : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'rnd'                           : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'whole'                         : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'strcmp'                        : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'strcasecmp'                    : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'strlen'                        : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'strmkupper'                    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'strmklower'                    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'strsearch'                     : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'ccom_search'                   : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'strfind'                       : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'h1flagmatch'                   : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'strlines'                      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'doclines'                      : (2, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'days_difference'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'days_add'                      : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'substring'                     : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'getlines'                      : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'atoi'                          : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'atof'                          : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'itoa'                          : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'ftoa'                          : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'testres_expand'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'strstr'                        : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'listgenerate'                  : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'listcount'                     : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'listelement'                   : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'an_results_match'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'an_results_flagged'            : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'an_error_check'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'an_event_log'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_set'                        : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_clear'                      : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_calculate'                  : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_value'                      : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_max_value'                  : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_min_value'                  : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_mean_value'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_median_value'               : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_freq'                       : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_max_freq'                   : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_min_freq'                   : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_mean_freq'                  : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_median_freq'                : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_name'                       : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'ee_plot'                       : (13, 0xFFFF, ''),  # EQTYPE_ALL
    'accept'                        : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'validate'                      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'validate_user'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'test_validated'                : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'test_result'                   : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'test_ordered'                  : (1, 0xFFFF, 'Checks lab->requests[] (does NOT include auto-added tests)'),  # EQTYPE_ALL
    'test_present'                  : (1, 0xFFFF, 'Checks lab->test[] (auto-added tests count as present)'),  # EQTYPE_ALL
    'test_modified'                 : (1, 0xFFFF, 'Compares against open-session snapshot only'),  # EQTYPE_ALL
    'retest_interval'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'test_loadvalue'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'test_setvalue'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'test_set_status'               : (2, 0x07F7, 'Only accepts 1 (<) or 2 (>); other values silently ignored'),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'test_check_status'             : (2, 0x07F7, 'Only accepts 1/2/3; other values return 0'),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'test_clear_status'             : (2, 0x07F7, 'Only accepts 1 (<) or 2 (>); other values silently ignored'),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'jump_to_test'                  : (1, 0x00B3, 'Only valid in Interactive eq types — TestRecalc/TestValidate/TestAccept/Request_Add/Request_Remove'),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_TESTACCEPT
    'add_request'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'remove_request'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'listinsert'                    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'listremove'                    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'listinsert_test'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'listremove_test'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'analyser'                      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'an_program'                    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'check_refrange'                : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'check_delta'                   : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'refrange'                      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'delta'                         : (1, 0x07F7, 'Returns BOOLEAN (1 if TESTSTATUS_DELTA set) — NOT the numeric delta amount'),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'checkbits'                     : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'setbits'                       : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'clearbits'                     : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'codedcomment'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'ccom_expand'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'testing_method'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'testing_lab'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'loadhistorical'                : (2, 0xFFFF, 'Validated only; requires current lab in UR list — returns 0 if lab not yet saved'),  # EQTYPE_ALL
    'loadcumulative'                : (2, 0xFFFF, 'Loads ALL results (incl unvalidated); only labs that had a cumulative report printed'),  # EQTYPE_ALL
    'loadcumulativereverse'         : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'loadlinkedresults'             : (2, 0xFFFF, 'Identical to loadhistorical in current code'),  # EQTYPE_ALL
    'loadlabrecs'                   : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'load_patsum_ur'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'load_patsum_lab'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'level1_status'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'an_result_status'              : (2, 0x0008, ''),  # EQTYPE_ANALYSER
    'an_change_test'                : (2, 0x0008, ''),  # EQTYPE_ANALYSER
    'output_text'                   : (6, 0x0040, ''),  # EQTYPE_REPORT
    'output_sigtext'                : (6, 0x0040, ''),  # EQTYPE_REPORT
    'output_box'                    : (7, 0x0040, ''),  # EQTYPE_REPORT
    'output_barcode'                : (8, 0x0040, ''),  # EQTYPE_REPORT
    'output_results'                : (10, 0x0040, ''),  # EQTYPE_REPORT
    'output_cumresults'             : (10, 0x0040, ''),  # EQTYPE_REPORT
    'output_units'                  : (8, 0x0040, ''),  # EQTYPE_REPORT
    'output_refrange'               : (8, 0x0040, ''),  # EQTYPE_REPORT
    'output_testmethod'             : (8, 0x0040, ''),  # EQTYPE_REPORT
    'output_lowprec'                : (8, 0x0040, 'Requires FSS licence'),  # EQTYPE_REPORT
    'output_highprec'               : (8, 0x0040, 'Requires FSS licence'),  # EQTYPE_REPORT
    'output_cumrefrange'            : (8, 0x0040, ''),  # EQTYPE_REPORT
    'output_cumgraph'               : (8, 0x0040, ''),  # EQTYPE_REPORT
    'output_testname'               : (10, 0x0040, 'test is LAST arg'),  # EQTYPE_REPORT
    'output_document'               : (9, 0x0040, ''),  # EQTYPE_REPORT
    'output_worddoc'                : (9, 0x0040, ''),  # EQTYPE_REPORT
    'output_eps'                    : (6, 0x0040, ''),  # EQTYPE_REPORT
    'output_control'                : (1, 0x0040, ''),  # EQTYPE_REPORT
    'output_raw'                    : (1, 0x0040, ''),  # EQTYPE_REPORT
    'output_hlseven'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'output_hl7'                    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'send_hl7'                      : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'send_sms'                      : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'output_rawimage'               : (6, 0x0040, ''),  # EQTYPE_REPORT
    'output_email'                  : (7, 0x0040, ''),  # EQTYPE_REPORT
    'output_url'                    : (7, 0x0040, ''),  # EQTYPE_REPORT
    'cumpageno'                     : (1, 0x0040, ''),  # EQTYPE_REPORT
    'output_sensitivities'          : (10, 0x0040, ''),  # EQTYPE_REPORT
    'output_uncertainty'            : (8, 0x0040, 'Requires uncertainty licence'),  # EQTYPE_REPORT
    'suppress_output'               : (1, 0x0040, ''),  # EQTYPE_REPORT
    'report_validated'              : (1, 0x0040, ''),  # EQTYPE_REPORT
    'lis_testlist'                  : (2, 0x0040, ''),  # EQTYPE_REPORT
    'lis_testcount'                 : (1, 0x0040, ''),  # EQTYPE_REPORT
    'result_format'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'result_format_images'          : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'cumresult_format'              : (3, 0xFFFF, 'Sets cumulative_A4 mode; use in A4 cumulative report context'),  # EQTYPE_ALL
    'result_count'                  : (1, 0xFFFF, 'Takes a comma-separated STRING (e.g. "SODIUM,POTASSIUM") — not a test identifier'),  # EQTYPE_ALL
    'result_match'                  : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'result_allow'                  : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'result_disallow'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'output_billing'                : (6, 0x0040, ''),  # EQTYPE_REPORT
    'output_publicbill'             : (10, 0x0040, ''),  # EQTYPE_REPORT
    'bill_line_set'                 : (5, 0x0040, ''),  # EQTYPE_REPORT
    'bill_mline_set'                : (6, 0x0040, ''),  # EQTYPE_REPORT
    'testres_encode'                : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'include_mask'                  : (1, 0xFFFF, 'Max 32 levels deep'),  # EQTYPE_ALL
    'loadfile'                      : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'duplicate_count'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'add_extra_copy'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'remove_extra_copy'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'mins_difference'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'document_repaginate'           : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'bill_gen_inv_text'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'output_inv_body'               : (4, 0x0040, ''),  # EQTYPE_REPORT
    'req_validate_orig'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'images_load'                   : (5, 0xFFFF, ''),  # EQTYPE_ALL
    'images_load_links'             : (5, 0xFFFF, ''),  # EQTYPE_ALL
    'image_output'                  : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'image_text'                    : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'image_width'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'image_height'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'image_count'                   : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'loadcrisps'                    : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'date_to_words'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'load_dnabatch'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'pdf_version'                   : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'output_signature'              : (5, 0xFFFF, ''),  # EQTYPE_ALL
    'annotate_value'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'annotate_text'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'annotate_select'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'annotate_load'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'output_line'                   : (7, 0x0040, ''),  # EQTYPE_REPORT
    'output_annoteimage'            : (5, 0x0040, ''),  # EQTYPE_REPORT
    'annoteimage_output'            : (7, 0x0040, ''),  # EQTYPE_REPORT
    'signoff_report'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'output_test_box'               : (7, 0x0040, ''),  # EQTYPE_REPORT
    'output_tm_alert'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'signoff_user'                  : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'get_file_lines'                : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'count_line_fields'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_line_field'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'is_field_valid'                : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'build_string'                  : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'dna_test'                      : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'add_dna_entry'                 : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'build_dna_entry'               : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'add_dna_string'                : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'decode_string'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'testlist_item'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'test_resultstring'             : (3, 0x0100, ''),  # EQTYPE_GENERIC
    'splitstr_count'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'splitstr_get'                  : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'gsi_status'                    : (4, 0x0100, ''),  # EQTYPE_GENERIC
    'allocate_labno'                : (0, 0x0100, ''),  # EQTYPE_GENERIC
    'allocate_urno'                 : (1, 0x0100, ''),  # EQTYPE_GENERIC
    'fetch_labur'                   : (2, 0x0100, ''),  # EQTYPE_GENERIC
    'fetch_lab'                     : (1, 0x0100, ''),  # EQTYPE_GENERIC
    'stripchars'                    : (2, 0x0100, ''),  # EQTYPE_GENERIC
    'test_on_lab'                   : (1, 0x0100, ''),  # EQTYPE_GENERIC
    'gsi_error_log'                 : (3, 0x0100, ''),  # EQTYPE_GENERIC
    'associate_crisp'               : (1, 0x0100, ''),  # EQTYPE_GENERIC
    'load_order_labs'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_order_value'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'get_form_value'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'get_paragraph'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'format_visit_hist'             : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'apply_stringency'              : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'add_dna_wflow'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'dna_wflow_result'              : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'dna_load_profile'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'dna_num_prof_items'            : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'dna_prof_items'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'dna_return_sample'             : (1, 0x0300, ''),  # EQTYPE_GENERIC | EQTYPE_AUTOVAL
    'get_storage_info'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_previousbatch'             : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'output_ncidd_xml'              : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'micro_setresult'               : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'micro_countresult'             : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'micro_suppress'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'micro_unsuppress'              : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'lab_processed'                 : (1, 0x0100, ''),  # EQTYPE_GENERIC
    'note_field'                    : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'outcum_pagecount'              : (3, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_testname'               : (12, 0x0040, 'Requires prior loadcumulative()'),  # EQTYPE_REPORT
    'outcum_units'                  : (11, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_refrange'               : (11, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_testmethod'             : (11, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_lowprec'                : (11, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_highprec'               : (11, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_results'                : (12, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_panelname'              : (12, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_accreditation'          : (9, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_guideline'              : (10, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_auditload'              : (3, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_auditpages'             : (1, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_audituser'              : (7, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_auditdate'              : (7, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_audittest'              : (7, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_auditlabg'              : (7, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_audittext'              : (7, 0x0040, ''),  # EQTYPE_REPORT
    'outcum_auditlab'               : (7, 0x0040, ''),  # EQTYPE_REPORT
    'load_user_details'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_xml_info'                  : (2, 0x0100, ''),  # EQTYPE_GENERIC
    'bsr_send_rtf'                  : (6, 0xFFFF, ''),  # EQTYPE_ALL
    'bsr_send_button'               : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'break_lines'                   : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'snomed_expand'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'specimen'                      : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'output_guideline'              : (7, 0x0040, 'Requires FSS licence'),  # EQTYPE_REPORT
    'output_accreditation'          : (6, 0x0040, ''),  # EQTYPE_REPORT
    'check_accreditation'           : (2, 0x0040, ''),  # EQTYPE_REPORT
    'nata_accred'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'accred_symbol'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_accred_status'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'output_panelname'              : (10, 0x0040, 'panel is LAST arg'),  # EQTYPE_REPORT
    'get_test_by_code'              : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'get_code_by_sys_test'          : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'output_testspecimen'           : (3, 0x0040, ''),  # EQTYPE_REPORT
    'output_fullcum'                : (13, 0x0040, ''),  # EQTYPE_REPORT
    'privilege'                     : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'an_result'                     : (1, 0x000C, 'Operates on raw LEVEL1_RESULT, not validated lab record'),  # EQTYPE_L1VALIDATE | EQTYPE_ANALYSER
    'unique_tube_count'             : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'get_unique_tube'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_count'                  : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_string'                 : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_txtheight'              : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'get_ab_count'                  : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'get_ab_string'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'is_eorder'                     : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_copyto'                 : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'add_uralert'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'set_pdfmode'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'set_abnormal'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'clear_abnormal'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'add_to_container'              : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'assign_order_id'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_source'                 : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'get_container'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_order_id'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_order_id_list'             : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'get_same_tube_tests'           : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'count_spare_containers'        : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'add_to_spare_containers'       : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'test_on_containers'            : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'add_antibiotics'               : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_billing_item'              : (2, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'set_billing_item'              : (3, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'get_billing_item_count'        : (0, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'ordering_lab'                  : (0, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'billing_lab'                   : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'test_val'                      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'test_res'                      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'check_locnum'                  : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'rule3_diagnosis'               : (2, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'ventana_update'                : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_subcount'               : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'eorder_substring'              : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'final_validation'              : (1, 0x0040, ''),  # EQTYPE_REPORT
    'isnoncum'                      : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'suppress_address'              : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'retrigger'                     : (0, 0x8000, 'Re-queues current equation; DEV-5812'),  # EQTYPE_RETRIGGER
    'eqlogging'                     : (2, 0xFFFF, 'level: 0=info, 1=warning, 2=error'),  # EQTYPE_ALL
    'batch_create'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'plate_search'                  : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'batch_store'                   : (0, 0xFFFF, ''),  # EQTYPE_ALL
    'find_batch_sample'             : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'find_batch_consum'             : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'find_batch_equip'              : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'find_batch_plate'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'find_batch_pos'                : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'find_batch_vuser'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'get_ab_list'                   : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'add_alert'                     : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'remove_alert'                  : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'alert_added'                   : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'output_accred_symbol'          : (6, 0x0040, ''),  # EQTYPE_REPORT
    'accred_report_statement'       : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'suppress_result'               : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'unsuppress_result'             : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'suppressed'                    : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'ei_suitability_override'       : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'organism_present'              : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'organism_group_present'        : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'organism_species_present'      : (1, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'organism_group_check'          : (2, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'organism_species_check'        : (2, 0x07F7, ''),  # EQTYPE_TESTRECALC | EQTYPE_TESTVALIDATE | EQTYPE_L1VALIDATE | EQTYPE_REQUEST_ADD | EQTYPE_REQUEST_RM | EQTYPE_REPORT | EQTYPE_TESTACCEPT | EQTYPE_GENERIC | EQTYPE_AUTOVAL | EQTYPE_REGISTRATION
    'an_add_test_result'            : (1, 0x0008, ''),  # EQTYPE_ANALYSER
    'add_labtm_spec_reqmt'          : (2, 0x0001, ''),  # EQTYPE_TESTRECALC
    'add_urtm_spec_reqmt'           : (2, 0x0001, ''),  # EQTYPE_TESTRECALC
    'add_testnote'                  : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'output_testnote'               : (7, 0x0040, ''),  # EQTYPE_REPORT
    'exp_ab_result'                 : (3, 0x0001, ''),  # EQTYPE_TESTRECALC
    'add_phone_notify'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'set_phone_notify'              : (4, 0xFFFF, ''),  # EQTYPE_ALL
    'get_phone_notify'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'add_urtm_antigen_neg_reqmt'    : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'testing_lab_check'             : (2, 0xFFFF, ''),  # EQTYPE_ALL
    'set_cancel_result_text'        : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'cancelled_requests'            : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'cancelled_reason'              : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'cancelled_contact'             : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'cancelled_time'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'cancelled_user'                : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'term_get_disp'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'term_get_pref'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'term_get_fsn'                  : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'term_get_cmurl'                : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'term_get_cmver'                : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'term_get_code'                 : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'output_codes'                  : (7, 0xFFFF, ''),  # EQTYPE_ALL
    'load_testnote'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'is_indication_code_present'    : (3, 0xFFFF, ''),  # EQTYPE_ALL
    'antibiotic_id'                 : (1, 0xFFFF, ''),  # EQTYPE_ALL
    'antibiotic_test_method'        : (2, 0xFFFF, ''),  # EQTYPE_ALL
}

# Total subroutines: 352
